// ──────────────────────────────────────────────────────────────────
// SLIDE MANIFEST — single source of truth for the converted PowerPoint slides that
// the Training Zone player shows in-lesson. Generated from the source decks; safe to
// hand-edit. To add the rest of a deck or a new deck, see docs/IMPORTING_SLIDES.md.
//
// Quick edit: every slide is one line in a deck's `slides` array (in slide order).
// Only `file` is required; `title`/`caption` are optional polish.
// ──────────────────────────────────────────────────────────────────

export interface ManifestSlide {
  /** File name inside client/public/slides/. */
  file: string;
  /** Optional learner-facing title. Falls back to "<deck> · Slide N". */
  title?: string;
  /** Optional learner-facing caption. Falls back to a generic in-platform note. */
  caption?: string;
  /**
   * Optional KPI scorecard id (see shared/kpiScorecards.ts). When set, the lesson
   * renders the live, per-client scorecard table over the slide image so targets
   * stay editable without re-exporting the deck.
   */
  scorecard?: string;
}

export interface SlideDeck {
  /** Stable deck id. */
  id: string;
  /** Display name of the source PowerPoint. */
  sourceDeck: string;
  /**
   * Module-id (and Switch-lane preview-id) prefixes that map to this deck.
   * Matched with String.startsWith, so "mod-wp" covers mod-wp-1/2/3.
   */
  modulePrefixes: string[];
  /** Ordered slides shown in the lesson (Previous/Next pages through these). */
  slides: ManifestSlide[];
}

export const slideDecks: SlideDeck[] = [
  {
    id: "softskills",
    sourceDeck: "Soft Skills & Customer/Patient Service Foundation",
    modulePrefixes: ["mod-sf", "mod-lfs", "mod-hcs"],
    slides: [
      { file: "softskills-01.jpg", title: "Soft Skills & Patient Service Foundations" },
      { file: "softskills-02.jpg", title: "Agenda" },
      { file: "softskills-03.jpg", title: "Patient Service Mindset & Training Overview" },
      { file: "softskills-04.jpg", title: "Why am I in training?" },
      { file: "softskills-05.jpg", title: "Soft Skills & Patient Service Foundations" },
      { file: "softskills-06.jpg", title: "Soft Skills & Patient Service Foundations" },
      { file: "softskills-07.jpg", title: "Soft Skills in Action" },
      { file: "softskills-08.jpg", title: "Communication" },
      { file: "softskills-09.jpg", title: "Empathy" },
      { file: "softskills-10.jpg", title: "Professionalism" },
      { file: "softskills-11.jpg", title: "What Great Service Looks Like" },
      { file: "softskills-12.jpg", title: "Group Discussion: What makes YOU trust a service provider?" },
      { file: "softskills-13.jpg" },
      { file: "softskills-14.jpg", title: "Communication Skills Deep Dive" },
      { file: "softskills-15.jpg", title: "Active Listening Overview" },
      { file: "softskills-16.jpg", title: "Ask–Probe–Confirm Model" },
      { file: "softskills-17.jpg", title: "Speaking with Clarity & Purpose" },
      { file: "softskills-18.jpg", title: "Positive vs Negative Language" },
      { file: "softskills-19.jpg", title: "Inspire Confidience vs Confusion" },
      { file: "softskills-20.jpg", title: "Partner Communication Practice" },
      { file: "softskills-21.jpg" },
      { file: "softskills-22.jpg", title: "Empathy & Emotional Intelligence" },
      { file: "softskills-23.jpg", title: "“I understand why you'd feel that way. Let me help make this easier for you.”" },
      { file: "softskills-24.jpg", title: "Emotional Cues Over the Phone" },
      { file: "softskills-25.jpg", title: "Rapport Without Going Too Deep" },
      { file: "softskills-26.jpg", title: "Communication Skills Deep Dive" },
      { file: "softskills-27.jpg", title: "Empathy vs Sympathy" },
      { file: "softskills-28.jpg", title: "Empathy Script Rewrite Activity" },
      { file: "softskills-29.jpg", title: "The Power of De-escalation" },
      { file: "softskills-30.jpg", title: "De-escalation & Difficult Calls" },
      { file: "softskills-31.jpg", title: "Why Patients Become Upset" },
      { file: "softskills-32.jpg", title: "The Escalation Curve" },
      { file: "softskills-33.jpg", title: "4-Step De-escalation Model" },
      { file: "softskills-34.jpg", title: "De-escalation Script Examples" },
      { file: "softskills-35.jpg", title: "Triad Activity: Difficult Call Roleplays" },
      { file: "softskills-36.jpg", title: "The Power of Professionalism & Branding" },
      { file: "softskills-37.jpg", title: "Professionalism & Brand Representation" },
      { file: "softskills-38.jpg", title: "Digital Professionalism Standards" },
      { file: "softskills-39.jpg", title: "Call Flow" },
      { file: "softskills-40.jpg", title: "Building Trust with Patients" },
      { file: "softskills-41.jpg", title: "Soft Skills Mini-Assessment" },
      { file: "softskills-42.jpg", title: "Scenario Quiz" },
      { file: "softskills-43.jpg", title: "Mini Roleplay Assessment" },
      { file: "softskills-44.jpg", title: "Key Takeaways" },
      { file: "softskills-45.jpg", title: "Group Debrief" },
      { file: "softskills-46.jpg", title: "Soft skills like communication, empathy, and professionalism are the cornerstone" },
    ],
  },
  {
    id: "qa",
    sourceDeck: "Quality Assurance Essentials",
    modulePrefixes: ["mod-wp", "preview-workflow"],
    slides: [
      { file: "qa-01.jpg", title: "Quality Assurance (QA) Essentials" },
      { file: "qa-02.jpg", title: "Quality Assurance (QA) Essentials" },
      { file: "qa-03.jpg", title: "Agenda Overview" },
      { file: "qa-04.jpg", title: "Key QA Responsibilities" },
      { file: "qa-05.jpg", title: "Why QA Exists" },
      { file: "qa-06.jpg", title: "How QA Supports Consistency and Customer Experience" },
      { file: "qa-07.jpg", title: "Expectations for Agents" },
      { file: "qa-08.jpg", title: "QA Metrics and Reporting" },
      { file: "qa-09.jpg", title: "Quality Assurance (QA) Essentials - Category Overview" },
      { file: "qa-10.jpg", title: "Greeting & Verification" },
      { file: "qa-11.jpg", title: "Soft Skills Scoring" },
      { file: "qa-12.jpg", title: "Accuracy Standards and Common Mistakes" },
      { file: "qa-13.jpg", title: "Compliance Requirements" },
      { file: "qa-14.jpg", title: "Documentation Quality" },
      { file: "qa-15.jpg", title: "What Excellence Looks Like" },
      { file: "qa-16.jpg", title: "Common Agent Mistakes" },
      { file: "qa-17.jpg", title: "Activity: QA Form Walk-Through" },
      { file: "qa-18.jpg", title: "Continuous Improvement" },
      { file: "qa-19.jpg", title: "Weighted Categories" },
      { file: "qa-20.jpg", title: "Quality Assurance (QA) Essentials" },
      { file: "qa-21.jpg", title: "Auto-Fail Criteria" },
      { file: "qa-22.jpg", title: "Activity: Score This Call Snippet" },
      { file: "qa-23.jpg", title: "QA Feedback Culture" },
      { file: "qa-24.jpg", title: "Reading QA Reviews Without Overwhelm" },
      { file: "qa-25.jpg", title: "Coachability & Growth Mindset" },
      { file: "qa-26.jpg", title: "QA Calibration Practice" },
      { file: "qa-27.jpg", title: "Calibration Steps" },
      { file: "qa-28.jpg", title: "Group Call Listening" },
      { file: "qa-29.jpg", title: "QA Technology Solutions" },
      { file: "qa-30.jpg", title: "Reveal: Official Score" },
      { file: "qa-31.jpg", title: "Self-Improvement Through QA" },
      { file: "qa-32.jpg", title: "Creating a Personal QA Plan" },
      { file: "qa-33.jpg", title: "Using QA Trends to Self-Correct" },
      { file: "qa-34.jpg", title: "Micro-Habits for Quality Success" },
      { file: "qa-35.jpg", title: "QA Mini Quiz" },
      { file: "qa-36.jpg", title: "Roleplay QA Scoring" },
      { file: "qa-37.jpg", title: "Great Work! You Are Building Strong Quality Skills" },
      { file: "qa-38.jpg", title: "Quality Assurance (QA) is the backbone of a successful call center operation, en" },
    ],
  },
  {
    id: "leadership-data",
    sourceDeck: "Unlocking the Power of Data",
    modulePrefixes: ["mod-dl", "mod-lfd", "preview-leadership"],
    slides: [
      { file: "leadership-data-01.jpg", title: "Unlocking the Power of Data: A Leadership Development Program for Contact Center" },
      { file: "leadership-data-02.jpg", title: "Module 1: Unlocking the Power of Data" },
      { file: "leadership-data-03.jpg", title: "What We'll Cover" },
      { file: "leadership-data-04.jpg", title: "SECTION 1 | READING AND UNDERSTANDING" },
      { file: "leadership-data-05.jpg", title: "Why Data Matters" },
      { file: "leadership-data-06.jpg", title: "Core KPIs Every Leader Must Understand" },
      { file: "leadership-data-07.jpg", title: "Core KPIs: Part 2" },
      { file: "leadership-data-08.jpg", title: "How to Read KPI Reports" },
      { file: "leadership-data-09.jpg", title: "Activity: Interpreting KPIs" },
      { file: "leadership-data-10.jpg", title: "SECTION 2: TRANSLATING DATA INTO ACTIONABLE INSIGHTS" },
      { file: "leadership-data-11.jpg", title: "From Data to Action" },
      { file: "leadership-data-12.jpg", title: "Root Cause Analysis Tools" },
      { file: "leadership-data-13.jpg", title: "Scenario: CSAT Drops" },
      { file: "leadership-data-14.jpg", title: "Turning Trends into Action Plans" },
      { file: "leadership-data-15.jpg", title: "Activity: From Insight to Action" },
      { file: "leadership-data-16.jpg", title: "Section 3" },
      { file: "leadership-data-17.jpg", title: "Examples of Flawed Analysis" },
      { file: "leadership-data-18.jpg", title: "Biases That Distort Data" },
      { file: "leadership-data-19.jpg", title: "Case Study: What Went Wrong?" },
      { file: "leadership-data-20.jpg", title: "Validating Your Conclusions" },
      { file: "leadership-data-21.jpg", title: "Section 4" },
      { file: "leadership-data-22.jpg", title: "Tools That Help You Analyze Data" },
      { file: "leadership-data-23.jpg", title: "Getting Value from Dashboards" },
      { file: "leadership-data-24.jpg", title: "Activity: Build a Simple Report View" },
      { file: "leadership-data-25.jpg", title: "Section 5" },
      { file: "leadership-data-26.jpg", title: "Success Story: Data in Action" },
      { file: "leadership-data-27.jpg", title: "Activity: Analyze the Story" },
      { file: "leadership-data-28.jpg", title: "Reflection: What Would You Do?" },
      { file: "leadership-data-29.jpg", title: "Key Takeaways" },
      { file: "leadership-data-30.jpg", title: "Putting This Into Practice" },
      { file: "leadership-data-31.jpg", title: "Unlocking the Power of Data: A Leadership Development Program for Contact Center" },
    ],
  },
  {
    id: "coaching",
    sourceDeck: "Real-time Coaching",
    modulePrefixes: ["mod-rtc", "preview-coaching"],
    slides: [
      { file: "coaching-01.jpg", title: "Leadership Development: Real-time Coaching" },
      { file: "coaching-02.jpg", title: "Welcome to Leadership Development: Real-time Coaching by CH Consulting Group. We" },
      { file: "coaching-03.jpg", title: "5 Coaching Pillars" },
      { file: "coaching-04.jpg", title: "How to Prepare, Approach, and Deliver Coaching and Feedback" },
      { file: "coaching-05.jpg", title: "Why we coach?: Real-time Coaching" },
      { file: "coaching-06.jpg", title: "How to Prepare for Effective Coaching" },
      { file: "coaching-07.jpg", title: "The Benefits of Setting SMART Goals" },
      { file: "coaching-08.jpg", title: "The Benefits of Holding Your Team Accountable" },
      { file: "coaching-09.jpg", title: "UNDERSTAND THE PURPOSE OF FEEDBACK" },
      { file: "coaching-10.jpg", title: "Coaching Through Discovery" },
      { file: "coaching-11.jpg", title: "Document Our Goals" },
      { file: "coaching-12.jpg", title: "Documenting Coaching Sessions" },
      { file: "coaching-13.jpg", title: "Smart Goal: Real-time Coaching" },
      { file: "coaching-14.jpg", title: "How to Write a SMART Goal Activity" },
      { file: "coaching-15.jpg", title: "Tailor Your Training to Fit Just Right" },
      { file: "coaching-16.jpg", title: "Exploring Different Learning Styles" },
      { file: "coaching-17.jpg", title: "Identifying an Agent's Learning Style" },
      { file: "coaching-18.jpg", title: "Customizing Your Coaching Approach for Different Learning Styles" },
      { file: "coaching-19.jpg", title: "Learning Style Identification Activity" },
      { file: "coaching-20.jpg", title: "Discerning Skill vs Will" },
      { file: "coaching-21.jpg", title: "Own the Message & Accountability Conversations" },
      { file: "coaching-22.jpg", title: "Why Owning the Message as a Leader is Critical" },
      { file: "coaching-23.jpg", title: "Owning the Message as a Leader" },
      { file: "coaching-24.jpg", title: "Strategies for Having a Difficult Conversation With Your Team Members" },
      { file: "coaching-25.jpg", title: "Delivering and Following Up on Corrective Action for Positive Results" },
      { file: "coaching-26.jpg", title: "Difficult Conversations Activity" },
      { file: "coaching-27.jpg" },
      { file: "coaching-28.jpg", title: "Wrapping Up: Recap & Conclusion of Coaching Workshop" },
      { file: "coaching-29.jpg", title: "Connect With CHCG Consulting" },
      { file: "coaching-30.jpg", title: "Our Team" },
    ],
  },
  {
    id: "performance-leadership",
    sourceDeck: "Utilizing Performance Management to Maximize Results",
    modulePrefixes: ["mod-lfp", "preview-performance"],
    slides: [
      { file: "performance-01.jpg", title: "Module 3: Utilizing Performance Management to Maximize Results" },
      { file: "performance-02.jpg", title: "Purpose of Module 3" },
      { file: "performance-03.jpg", title: "Why Performance Management Matters" },
      { file: "performance-04.jpg", title: "The 3 Performance Buckets (Overview)" },
      { file: "performance-05.jpg", title: "High Performers: Characteristics" },
      { file: "performance-06.jpg", title: "Mid Performers: Characteristic" },
      { file: "performance-07.jpg", title: "Low Performers: Characteristics" },
      { file: "performance-08.jpg", title: "Bucketing Activity" },
      { file: "performance-09.jpg", title: "Avoiding Mislabeling & Bias" },
      { file: "performance-10.jpg", title: "Using QA to Drive Coaching" },
      { file: "performance-11.jpg", title: "Calibration: Ensuring Objective Evaluations" },
      { file: "performance-12.jpg", title: "INSERT CLIENT QA FORM" },
      { file: "performance-13.jpg", title: "Identifying Performance Levels Accurately" },
      { file: "performance-14.jpg", title: "Discovery Tools" },
      { file: "performance-15.jpg", title: "Engaging and Developing High Performers" },
      { file: "performance-16.jpg", title: "Engaging and Developing High Performers" },
      { file: "performance-17.jpg", title: "Coaching the \"Movable Middle\"" },
      { file: "performance-18.jpg", title: "Strategies for Addressing Low Performance" },
      { file: "performance-19.jpg", title: "Progressive Discipline Done Right" },
      { file: "performance-20.jpg", title: "Building an Effective PIP" },
      { file: "performance-21.jpg", title: "Activity: Build a Tailored Performance Plan" },
      { file: "performance-22.jpg", title: "Coaching to Improve Adherence" },
      { file: "performance-23.jpg", title: "Leadership Rituals that Improve Results Daily" },
      { file: "performance-24.jpg", title: "Reflection: What Will You Change Tomorrow?" },
      { file: "performance-25.jpg", title: "Key Takeaways from Module 3" },
    ],
  },
  {
    id: "gamification",
    sourceDeck: "Gamification for Remote Teams: Engaging and Empowering Leaders",
    modulePrefixes: ["mod-hce", "preview-engagement", "mod-hcd"],
    slides: [
      { file: "engagement-01.jpg", title: "Gamification for Remote Teams: Engaging and Empowering Leaders" },
      { file: "engagement-02.jpg", title: "Work-at-Home Leadership Strategies" },
      { file: "engagement-03.jpg", title: "Leading WAH Teams With Confidence" },
      { file: "engagement-04.jpg", title: "WAH Daily Operating Rhythm" },
      { file: "engagement-05.jpg", title: "WAH Summary" },
      { file: "engagement-06.jpg", title: "What Is Gamification?" },
      { file: "engagement-07.jpg", title: "Introduction to Gamification" },
      { file: "engagement-08.jpg", title: "Why Engagement Matters in WAH Teams" },
      { file: "engagement-09.jpg", title: "The Foundation of Engagement" },
      { file: "engagement-10.jpg", title: "How to Build a Successful Gamification Program" },
      { file: "engagement-11.jpg", title: "What Makes a Good Reward?" },
      { file: "engagement-12.jpg", title: "Key Gamification Concepts and Techniques" },
      { file: "engagement-13.jpg", title: "Gamification Mistakes to Avoid" },
      { file: "engagement-14.jpg", title: "Key Gamification Concepts" },
      { file: "engagement-15.jpg", title: "Activity: What Games Would Work for Your Team?" },
      { file: "engagement-16.jpg", title: "Balancing Competition & Collaboration" },
      { file: "engagement-17.jpg", title: "Designing Effective Gamification Programs" },
      { file: "engagement-18.jpg", title: "Integrating Gamification Into Daily Routines" },
      { file: "engagement-19.jpg", title: "Team Spirit & Remote Culture Boosters" },
      { file: "engagement-20.jpg", title: "Recognition in Remote Teams" },
      { file: "engagement-21.jpg", title: "Remote Recognition Workshop" },
      { file: "engagement-22.jpg", title: "Measuring Engagement" },
      { file: "engagement-23.jpg", title: "Gamification for Remote Teams: Engaging and Empowering Leaders" },
      { file: "engagement-24.jpg", title: "Surveys & Pulse Checks" },
      { file: "engagement-25.jpg", title: "Adjust & Right Set" },
      { file: "engagement-26.jpg", title: "Go Put It Into Practice" },
      { file: "engagement-27.jpg", title: "Reflection Slide" },
    ],
  },
  {
    id: "wfm-kpi",
    sourceDeck: "Workforce Management & KPIs",
    modulePrefixes: ["mod-wfm", "preview-wfm"],
    slides: [
      { file: "wfm-kpi-01.jpg", title: "Workforce Management & Key Performance Indicators (KPIs)" },
      { file: "wfm-kpi-02.jpg", title: "Workforce Management & Key Performance Indicators (KPIs)" },
      { file: "wfm-kpi-03.jpg", title: "What is WFM?" },
      { file: "wfm-kpi-04.jpg", title: "What Is WFM? (Definition)" },
      { file: "wfm-kpi-05.jpg", title: "Who is WFM?" },
      { file: "wfm-kpi-06.jpg", title: "Key Workforce Management Components" },
      { file: "wfm-kpi-07.jpg", title: "Forecasting, Staffing & Scheduling Overview" },
      { file: "wfm-kpi-08.jpg", title: "Why WFM Matters to Agents" },
      { file: "wfm-kpi-09.jpg", title: "Workforce Management & Key Performance Indicators (KPIs)" },
      { file: "wfm-kpi-10.jpg", title: "Adherence & Scheduling" },
      { file: "wfm-kpi-11.jpg", title: "Scheduling & Adherence" },
      { file: "wfm-kpi-12.jpg", title: "Adherence & Attendance" },
      { file: "wfm-kpi-13.jpg", title: "How Schedules Are Built" },
      { file: "wfm-kpi-14.jpg", title: "Interval-Based Planning" },
      { file: "wfm-kpi-15.jpg", title: "Break & Lunch Adherence" },
      { file: "wfm-kpi-16.jpg", title: "Which Scenario Breaks Adherence?" },
      { file: "wfm-kpi-17.jpg", title: "Productivity & Efficiency" },
      { file: "wfm-kpi-18.jpg", title: "AUX Codes & System States – Finesse" },
      { file: "wfm-kpi-19.jpg", title: "AUX Codes & System States – Calabrio" },
      { file: "wfm-kpi-20.jpg", title: "AUX Codes & System States – Calabrio Cont." },
      { file: "wfm-kpi-21.jpg", title: "Early/Late Return Impacts" },
      { file: "wfm-kpi-22.jpg", title: "Occupancy" },
      { file: "wfm-kpi-23.jpg", title: "Utilization" },
      { file: "wfm-kpi-24.jpg", title: "Handle Time Efficiency" },
      { file: "wfm-kpi-25.jpg", title: "Productivity Challenge" },
      { file: "wfm-kpi-26.jpg", title: "Avoiding Productivity Traps" },
      { file: "wfm-kpi-27.jpg", title: "KPI Deep Dive" },
      { file: "wfm-kpi-28.jpg", title: "Workforce Management & KPIs" },
      { file: "wfm-kpi-29.jpg", title: "KPI Scorecard — Patient Service", scorecard: "patient-service" },
      { file: "wfm-kpi-30.jpg", title: "KPI Scorecard — Efficiency", scorecard: "efficiency" },
      { file: "wfm-kpi-31.jpg", title: "KPI Scorecard — WFM", scorecard: "wfm" },
      { file: "wfm-kpi-32.jpg", title: "Workforce Management & Key Performance Indicators (KPIs) - After-Call Work (ACW)" },
      { file: "wfm-kpi-33.jpg", title: "What is ACW?" },
      { file: "wfm-kpi-34.jpg", title: "The Impact of ACW on Productivity" },
      { file: "wfm-kpi-35.jpg", title: "Benefits of Optimizing ACW" },
      { file: "wfm-kpi-36.jpg", title: "Quality Score Impact on Agent Performance" },
      { file: "wfm-kpi-37.jpg", title: "Workforce KPIs: Measuring Success" },
      { file: "wfm-kpi-38.jpg", title: "How KPIs Interact" },
      { file: "wfm-kpi-39.jpg", title: "Patient Satisfaction (CSAT) and Net Promoter Score (NPS)" },
      { file: "wfm-kpi-40.jpg", title: "First Call Resolution (FCR)" },
      { file: "wfm-kpi-41.jpg", title: "Workforce Scheduling & Optimization" },
      { file: "wfm-kpi-42.jpg", title: "Agent Dashboards & Scorecard" },
      { file: "wfm-kpi-43.jpg", title: "Dashboard" },
      { file: "wfm-kpi-44.jpg", title: "When to Ask for Support" },
      { file: "wfm-kpi-45.jpg", title: "Workforce Management & Key Performance Indicators (KPIs)" },
      { file: "wfm-kpi-46.jpg", title: "Knowledge Check" },
      { file: "wfm-kpi-47.jpg", title: "Short Quiz" },
      { file: "wfm-kpi-48.jpg", title: "You Now Understand the Metrics That Drive Your Success" },
    ],
  },
];

/** Derive a "Slide N" page label from a slide filename like "qa-10.jpg". */
export function slidePageLabel(file: string): string {
  const match = file.match(/-(\d+)(?:_|\.)/);
  return match ? `Slide ${Number.parseInt(match[1], 10)}` : "Slide";
}

/** The deck whose module-id prefixes match this module, or null if none. */
export function slideDeckForModuleId(moduleId: string): SlideDeck | null {
  return slideDecks.find((deck) => deck.modulePrefixes.some((prefix) => moduleId.startsWith(prefix))) ?? null;
}
